<?php


use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Tester\CommandTester;

class DataExporterTest extends KernelTestCase
{

    private InputInterface $inputInterface;
    private OutputInterface $outputInterface;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::bootKernel();

        $this->inputInterface = $this->createMock(InputInterface::class);
        $this->outputInterface = $this->createMock(OutputInterface::class);
    }

    public function testExecute(){
        $app =  new Application(self::$kernel);
        //command = $app->find('app:myCommand');
        //$import  = $this->createMock(DataExporter::class);
        //$result = new CommandTester($command);
        //dd($result->execute($this->inputInterface, $this->outputInterface));

    }
}