<?php

declare(strict_types=1);

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class DataExporterTest extends KernelTestCase
{


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::bootKernel();

        //$this->inputInterface = $this->createMock(InputInterface::class);
        //$this->outputInterface = $this->createMock(OutputInterface::class);
    }

    public function testExecute(){
        //$app =  new Application(self::$kernel);
        //command = $app->find('app:myCommand');
        //$import  = $this->createMock(DataExporter::class);
        //$result = new CommandTester($command);
        //dd($result->execute($this->inputInterface, $this->outputInterface));

        $this->assertTrue(true);

    }
}