# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Service\XmlExporterService:
        arguments:


    App\Service\XmlFileReaderService:
        arguments:
            $resourceDir: '%kernel.project_dir%/resource/'
            $ftpHost: '%env(FTP_HOST)%'
            $ftpUser: '%env(FTP_USER)%'
            $ftpPassword: '%env(FTP_PASSWORD)%'

    GoogleClient:
        class: Google_Client
        autowire: true
        calls:
            - [setApplicationName, ['DataExporter XML to google sheet']]
            - [setScopes, ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']]
            - [setAccessType, ['offline']]
            - [setAuthConfig, ['%kernel.project_dir%%env(GC_AUTH_CONFIG)%']]

    GoogleServiceSheets:
        class: Google_Service_Sheets
        arguments:
            - '@GoogleClient'

    GoogleServiceDrive:
        class: Google_Service_Drive
        arguments:
            - '@GoogleClient'

    App\Component\GoogleAPI\GoogleSpreadSheetAPI:
        arguments:
            $googleClient: '@GoogleClient'
            $googleSheet: '@GoogleServiceSheets'
            $googleDrive: '@GoogleServiceDrive'
            $sheetName: 'Sheet1'





    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones